# Do not modify this file!  It was generated by ‘nixos-generate-config’
# and may be overwritten by future invocations.  Please make changes
# to /etc/nixos/configuration.nix instead.
{ config, lib, pkgs, modulesPath, ... }:

{
  imports =
    [ (modulesPath + "/installer/scan/not-detected.nix")
    ];

  boot.initrd.availableKernelModules = [ "nvme" "xhci_pci" "dm_crypt" "thunderbolt" "usb_storage" "sd_mod" ];
  boot.initrd.kernelModules = [ "dm_crypt" "nvme" "nvme_core" "sd_mod" ];
  boot.initrd.systemd.enable = false;
  boot.kernelModules = [ "kvm-amd" ];
  boot.extraModulePackages = [ ];
  boot.kernelParams = [ "rd.debug" "rd.luks.debug" ];

  fileSystems."/" =
    { device = "/dev/mapper/luks-3c27f4af-5131-4f6a-90c0-40c1fda781fd";
      fsType = "ext4";
    };

  boot.initrd.luks.devices."luks-3c27f4af-5131-4f6a-90c0-40c1fda781fd".device = "/dev/disk/by-uuid/3c27f4af-5131-4f6a-90c0-40c1fda781fd";

  fileSystems."/boot" =
    { device = "/dev/disk/by-uuid/921D-CCD3";
      fsType = "vfat";
      options = [ "fmask=0077" "dmask=0077" ];
    };

  swapDevices = [ ];

  nixpkgs.hostPlatform = lib.mkDefault "x86_64-linux";
  hardware.cpu.amd.updateMicrocode = lib.mkDefault config.hardware.enableRedistributableFirmware;
}
